
#Database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/sbb?serverTimezone=Asia/Seoul

  #JPA
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

